version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu    

hooks:
  ApplicationStop:
    - location: server_stop.sh
      timeout: 20
      runas: root
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: root
    - location: install_dependencies.sh
      timeout: 300
      runas: root 
  AfterInstall:
    - location: privileges.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
