version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Entered the install phase... 
      - apt update -y
      - apt install -y maven
    finally:
      - echo This always runs even if the update or install command fails  
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - cd ./src
      - pwd
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - src/web/app/target/*.war
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes

#cache:
 # paths:
  #- '/root/.m2/**/*'
